**<title>Numpy Exercise 1</title>**

**<h1>Numpy Exercise</h1>**

<hr>

*numpy documentation: https://numpy.org/doc/stable/

In [128]:
# Import library
import numpy as np

# Agar saat generate bilangan random hasilnya konsisten
np.random.seed(0)

## **No.1**

Buatlah sebuah array 1 dimensi (vektor) yang diisi dengan 36 elemen. Isi dari array
tersebut adalah bilangan random yang dibangkitkan dari rentang nilai 1 hingga 100.
Simpan array tersebut dalam sebuah variable bernama myArray, kemudian coba
tampilkan!

In [129]:
myArray = np.random.randint(1, 100, 36)
myArray

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30], dtype=int32)

## **No.2**

Dari myArray, bentuklah 3 array dengan bentuk yang berbeda (mengganti dimensi
matriksnya) dengan kombinasi ukuran yang berbeda beda!
- Matriks berukuran 2x18
- Matriks berukuran 9x4
- Array 3 Dimensi berukuran 2x6x3

In [130]:
myArray2x18 = myArray.reshape(2, 18)
myArray2x18

array([[45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66,
        40, 88],
       [47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
        50, 30]], dtype=int32)

In [131]:
myArray9x4 = myArray.reshape(9, 4)
myArray9x4

array([[45, 48, 65, 68],
       [68, 10, 84, 22],
       [37, 88, 71, 89],
       [89, 13, 59, 66],
       [40, 88, 47, 89],
       [82, 38, 26, 78],
       [73, 10, 21, 81],
       [70, 80, 48, 65],
       [83, 89, 50, 30]], dtype=int32)

In [132]:
myArray2x6x3 = myArray.reshape(2, 6, 3)
myArray2x6x3

array([[[45, 48, 65],
        [68, 68, 10],
        [84, 22, 37],
        [88, 71, 89],
        [89, 13, 59],
        [66, 40, 88]],

       [[47, 89, 82],
        [38, 26, 78],
        [73, 10, 21],
        [81, 70, 80],
        [48, 65, 83],
        [89, 50, 30]]], dtype=int32)

## **No.3**

Berapakah nilai minimun dan maksimum dari myArray? Tampilkan dan coba perlihatkan
nilai maksimum dan minimum tersebut ada pada indeks keberapa!

In [133]:
myArray.min()

np.int32(10)

In [134]:
myArray.argmin()

np.int64(5)

In [135]:
myArray.max()

np.int32(89)

In [136]:
myArray.argmax()

np.int64(11)

## **No.4**

Buatlah sebuah array baru dari myArray dengan data yang diambil berasal dari index 3,
5, 30, 12, 15, 8, 24, 14, 22. Setelah itu, reshape bentuknya menjadi sebuah matrix
ukuran 3x3!

In [137]:
fancyArray = myArray[[3, 5, 30, 12, 15, 8, 24, 14, 22]]
matrixArray = fancyArray.reshape(3,3)
matrixArray

array([[68, 10, 48],
       [89, 66, 37],
       [73, 59, 26]], dtype=int32)

## **No.5**
Dari matrix yang dibuat pada nomor 4, tampilkan data yang nilainya lebih besar dari 50!

In [138]:
matrixArray[matrixArray > 50]

array([68, 89, 66, 73, 59], dtype=int32)

## **No.6**
Buat sebuah array menggunkan salah satu method di numpy dengan output seperti di
bawah ini! <br>
`array([  0,  25,  50,  75, 100])`

In [139]:
myArray = np.arange(0, 101, 25)
myArray

array([  0,  25,  50,  75, 100])

## **No.7**
Buatlah sebuah array 2 dimensi dengan ukuran NxN di mana N nya adalah sebuah
inputan. Isi dari array tersebut seluruhnya adalah angka 8!

In [140]:
input = 3
myArray = np.random.randint(8, 9, size=(input, input))
myArray

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)

## **No.8**

- Buatlah 2 buah array 2 dimensi seperti gambar di bawah ini, lalu simpan dalam variabel
bernama arrayA dan arrayB!<br>

```
arrayA
array([[ 1,  2,  3,  4]
       [ 5,  6,  7,  8]
       [ 9, 10, 11, 12]])
```

```
arrayB
array([[100],
       [200],
       [300],
       [400]])
```


- Buatlah sebuah array yang berasal dari gabungan arrayA dan arrayB seperti gambar di
bawah ini, simpan dalam variabel bernama arrayC!

```
array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])
```

In [141]:
arrayA = np.arange(1, 13).reshape(3, 4)
arrayB = np.arange(100, 401, 100).reshape(4, 1)
arrayC = np.concatenate((arrayA, arrayB.T), axis=0)
arrayC

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

## **No.9**

Dari arrayC, lakukan slicing agar menghasilkan array di bawah ini!
```
array([[ 7,  8],
       [11, 12]])
```


In [142]:
arrayCustom = arrayC[1:3, 2:4]
arrayCustom

array([[ 7,  8],
       [11, 12]])

## **No.10**
Dari arrayC, lakukan indexing untuk mendapatkan angka 200!

In [143]:
angka200 = np.where(arrayC == 200)
angka200

(array([3]), array([1]))

## **No. 11**
Dari 2 array berikut, tampilkan index yang nilainya sama antara array a dan b.

In [144]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Output:
# array([1, 3, 5, 7])

np.where(a == b)

(array([1, 3, 5, 7]),)

## **No. 12**

Dari array berikut, tampilkan nilai yang range-nya antara 5 dan 10!

In [145]:
x = np.array([2, 6, 1, 9, 10, 3, 27])

# Output:
# array([6, 9, 10])

x[(x >= 5) & (x <= 10)]

array([ 6,  9, 10])

## **No. 13**

Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3) <br>
outputnya adalah:
```
array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
```
Bagaimana mengubah output di atas menjadi seperti berikut?
```
 array([[1, 0, 2],
        [4, 3, 5],
        [7, 6, 8]])
```

In [146]:
arr = np.arange(9).reshape(3, 3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [147]:
arr[0, 0], arr[0, 1] = arr[0, 1], arr[0, 0]
arr[1, 0], arr[1, 1] = arr[1, 1], arr[1, 0]
arr[2, 0], arr[2, 1] = arr[2, 1], arr[2, 0]

arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## **No. 14**

Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3)<br>
outputnya adalah: <br>
```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

Bagaimana mengubah output di atas menjadi seperti berikut?<br>
Output: <br>
```
array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])
```

In [148]:
arr = np.arange(9).reshape(3, 3)

arr[0, 0], arr[1, 0] = arr[1, 0], arr[0, 0]
arr[0, 1], arr[1, 1] = arr[1, 1], arr[0, 1]
arr[0, 2], arr[1, 2] = arr[1, 2], arr[0, 2]

arr

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## **No. 15**

15. Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3)<br>
outputnya adalah:
```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

Bagaimana mengubah output di atas menjadi seperti berikut?<br>

Output:<br>
```
array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])
```

In [149]:
arr = np.arange(9).reshape(3, 3)

arr[0, 0], arr[0, 2] = arr[0, 2], arr[0, 0]
arr[1, 0], arr[1, 2] = arr[1, 2], arr[1, 0]
arr[2, 0], arr[2, 2] = arr[2, 2], arr[2, 0]

arr

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## **No. 16**

Perhatikan array multidimensi berikut.<br>
```
arr_1 = np.array([
    [7, 8, 9, 4, 3],
    [5, 6, 2, 1, 0],
    [3, 8, 4, 7, 2],
    [9, 3, 5, 6, 1],
    [0, 1, 2, 8, 4]
])
```
Modifikasi lah array di atas sehingga menjadi dua buah matriks baru, matriks diagonal dan matriks segitiga atas.

Output
```
[[7 0 0 0 0]
 [0 6 0 0 0]
 [0 0 4 0 0]
 [0 0 0 6 0]
 [0 0 0 0 4]]

[[7 8 9 4 3]
 [0 6 2 1 0]
 [0 0 4 7 2]
 [0 0 0 6 1]
 [0 0 0 0 4]]
 ```

In [154]:
arr_1 = np.array([
    [7, 8, 9, 4, 3],
    [5, 6, 2, 1, 0],
    [3, 8, 4, 7, 2],
    [9, 3, 5, 6, 1],
    [0, 1, 2, 8, 4]
])

In [156]:
matriks_diagonal = np.diag(np.diag(arr_1))
matriks_diagonal

array([[7, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 4]])

In [155]:
matriks_segitiga_atas = np.triu(arr_1)
matriks_diagonal

array([[7, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 4]])

## **No. 17**

Terdapat beberapa *array* multidimensi sebagai berikut.
```
A = np.array([[7, 8, 5, 3], [2, 9, 4, 6], [3, 7, 1, 8], [5, 2, 6, 4]])
B = np.array([[3, 6, 8, 2], [4, 5, 7, 1], [9, 2, 3, 6], [1, 7, 5, 8]])
C = np.array([[5, 9, 3, 7], [1, 6, 4, 2], [8, 3, 5, 1], [2, 7, 9, 4]])
D = np.array([[6, 3, 5, 8], [2, 7, 9, 4], [1, 8, 6, 2], [5, 4, 3, 7]])
```
Dari keempat multidimensi array di atas, lakukanlah langkah-langkah berikut ini.
1. Cari absolute dari pengurangan antara A dan C yang kemudian dijumlahi hasil pengurangan B dan D
2. Buat matrix baru yang isinya adalah hasil kuadrat tiap elemen dari matrix pada langkah 1
3. Jalankan operasi invers pada matrix pada langkah 2
4. Terapkan operasi penjumlahan antara matrix pada langkah 3 dengan matriks C
5. Jalankan perkalian skalar pada matrix D dengan hasil pada langkah 4
*hint*: anda dapat menggunakan fungsi `sqrt()`

Secara matematis, langkah di atas dapat dituliskan sebagai berikut.
1. $V = |A - C + (B - D)|$
2. $W = V^{2}$
3. $X = W^{-1}$
4. $Y = X + C$
5. $result = Y*D$

Print multidimensi array dari ```result```

note: untuk perkalian matrix gunakan operasi *

Output
```
[[30.18326693 27.41434263 14.86968792 55.68791501]
 [ 2.00885347 41.83576804 35.9497012   9.02810978]
 [ 7.92297477 23.53253652 30.38346614  2.05544489]
 [10.14386897 28.05666224 26.95351926 27.88224878]]
 ```

## **No. 18**

Terdapat sebuah array sebagai berikut.
```
arr_3 = np.array([ 64, 152, 120, 136, 112,  80,  48,  40, 144,  72,  16,  56,  24, 160,  32, 104,  96,   8,  88, 128])
```
Untuk setiap elemen arr_3, bagi setiap angka dalam array dengan 8 dan kemudian hitung serta tampilkan rata-rata, median, nilai minimum, standar deviasi, variance, dan percentile 70!

Output
```
matriks dibagi 8: [ 8. 19. 15. 17. 14. 10.  6.  5. 18.  9.  2.  7.  3. 20.  4. 13. 12.  1.
 11. 16.]
Rata-rata: 10.5
Median: 10.5
Nilai Minimum: 1.0
Standar Deviasi: 5.766281297335398
Variance: 33.25
Percentile 70: 14.299999999999999
```